apiVersion: autoscaling/v1
kind: VerticalPodAutoscaler
metadata:
  name: frontend
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  targetCPUUtilizationPercentage: 15